### ISSUE TITLE
How to use save as SVG option in offline wavedrom editor

### ISSUE THREAD

**Issue by ideasdeepak** [drom/wavedrom#101]
First of all, I would like to congratulate and convey my hearty wishes to giving such a wonderful timing diagram tool. I have sit and used it just for half an hour and got to know each and every options. But, I have faced some problems like save as SVG. I have downloaded wavedrom offline tool from github. I have made some timing diagrams and try to save it as a SVG format through that offline tool using save as SVG option. But, unable to save it. I am having windows 7 OS...

I would like to know, is there a way to save the file as .svg from offline wavedrom tool or do I need to add any supporting codes, if yes, please instruct me what to do?.

Regards,
Deepak

**Comment by drom** [comment]
should be fixed in v0.11.2

**Comment by yunqu** [comment]
Is there a way to save wavedrom into SVG file without using any GUI? I would not use wavedrom-cli since phantomJS is too heavy.

**Comment by drom** [comment]
@yunqu PantomJS is ~15-20MB depend on platform. What are your platform requirements? What OS?

**Comment by yunqu** [comment]
@drom  It is arm-v71. Ubuntu 15.10.

**Comment by drom** [comment]
@yunqu do you have nodejs on your platform?

**Comment by yunqu** [comment]
@drom node -v gives me v6.2.2.

**Comment by drom** [comment]
Here is an open issue for making WaveDrom a DOM-less node app: https://github.com/drom/wavedrom/issues/128
