### ISSUE TITLE
Undefined node switches screen to error screen

### ISSUE THREAD

**Issue by mizzihood** [drom/wavedrom#104]
If an undefined node is referenced in "edge" section, screen is switched to an error screen causing work to be lost:
Example:

{signal: [
  {name: 'sig_a',       wave: 'p......'          , period:1          , node:'ab.'         }
 ],
edge: [
    'a~c'
]
}
![screenshot from 2014-11-03 15 36 26](https://cloud.githubusercontent.com/assets/9532099/4883891/d915442c-6366-11e4-93f7-4670d24a251d.png)

(c is not a defined node)

**Comment by drom** [comment]
Should be fixed in v0.11.2
