### ISSUE TITLE
Expand URL is not working

### ISSUE THREAD

**Issue by yinhaoliew** [drom/wavedrom#105]
### Issue Summary:
Using the URL from "Expand URL", it shows the json code (saved in cookies) and the waveform is not displaying.

### Step to reproduce:
1. to go http://wavedrom.com/editor.html
2. make some changes to json
3. select "Expand URL" from the "menu" (3 horizontal bar icon)
4. copy the URL from the browser address bar
5. open a new browser page, and paste the URL in the address bar.

### Example URL:
http://wavedrom.com/editor.html?%7Bsignal%3A%20%5B%0A%20%20%7Bname%3A%20%27clk%27%2C%20wave%3A%20%27p.....%7C...%27%7D%2C%0A%20%20%7Bname%3A%20%27dat%27%2C%20wave%3A%20%27x.345x%7C%3D.x%27%2C%20data%3A%20%5B%27head%27%2C%20%27body%27%2C%20%27tail%27%2C%20%27data%27%5D%7D%2C%0A%20%20%7Bname%3A%20%27req%27%2C%20wave%3A%20%270.1..0%7C1.0%27%7D%2C%0A%20%20%7B%7D%2C%0A%20%20%7Bname%3A%20%27ack%27%2C%20wave%3A%20%271.....%7C01.%27%7D%0A%5D%7D%0A

**Comment by drom** [comment]
should work in v0.11.2
