### ISSUE TITLE
EPS export

### ISSUE THREAD

**Issue by drom** [drom/wavedrom#138]
Microsoft Word can't handle SVG, but accepts EPS.
Export should be possible.
Here example of PS project.
https://github.com/jbush001/DrawWaveform
http://www-rohan.sdsu.edu/~aty/bibliog/latex/PSandEPS.html
https://en.wikipedia.org/wiki/PostScript
https://en.wikipedia.org/wiki/Encapsulated_PostScript
http://www.mostlymaths.net/2008/12/quick-postscript-programming-tutorial.html

have to learn PS. again.

**Comment by polpo** [comment]
AFAIK, word can place an EPS file, but doesn't actually interpret the PostScript. It will send the PS to a PS printer or PDF, but for any other output format it uses the preview image attached to the EPS, which is usually very low resolution.

Word does understand the WMF and EMF formats as vectors, though.

**Comment by drom** [comment]
@polpo thank you for the information. I am fine with M$ forwarding EPS to the printer. Can we sneak in hi-res preview into EPS?
I am not big fan of WMF, EMF, but have you seen ant good docs on the format?

**Comment by drom** [comment]
@polpo here is one more thread on the issue: https://groups.google.com/d/topic/microsoft.public.mac.office.word/nxLC9R1r4jg/discussion
Looks like you are absolutely right. EPS is not an option, because M$ may print bitmap or vector depend on the printer.
WMF/EMF is a can of worms, an I don't even want opening it. So, pass for now.

**Comment by drom** [comment]
Duplicate of #37
