### ISSUE TITLE
Wavedrom in mediawiki

### ISSUE THREAD

**Issue by Martoni** [drom/wavedrom#144]
Does somebody know how to integrate wavedrom in mediawiki ?

**Comment by drom** [comment]
@Martoni It would be cool :+1:
It should not be too difficult to do. Do you have good mediawiki plugin template? example?
Does anybody have access to mediawiki installation to try?

**Comment by Martoni** [comment]
@drom Yes I have an access to a mediawiki installation. I've got a private mediawiki. But I don't know how to make a plugin template.
I'll keep trying to do it, if I find how to I will explain it here.

**Comment by Martoni** [comment]
@drom I wrote a [quick&dirty plugin](https://github.com/Martoni/mediawiki_wavedrom). It works for me, but not perfect.

**Comment by drom** [comment]
Great job. That was quick!

**Comment by Martoni** [comment]
and dirty ;)

**Comment by drom** [comment]
It is fine. Keep working and you will make it clean :smirk:
