### ISSUE TITLE
unicode text breaks SVG/PNG export

### ISSUE THREAD

**Issue by udif** [drom/wavedrom#168]
A simple Diagram I created will no longer export when I paste a unicode symbol inside the label.
Minimal example:

{signal: [
  {name: 'Out', wave: '2|', data: ['ΣA']}
 ],
}

I also tried entering the unicode character as \u03a3 . It renders fine, but ultimately it still breaks the export.

**Comment by drom** [comment]
Duplicate of #137 and belongs here https://github.com/wavedrom/wavedrom.github.io/issues/17

**Comment by drom** [comment]
Fixed in v1.4.2
https://github.com/wavedrom/wavedrom.github.io/releases/tag/v1.4.2
