### ISSUE TITLE
Undo Proportions?

### ISSUE THREAD

**Issue by deathbysushi** [drom/wavedrom#170]
I clicked on the proportions options in the bottom right menu and the code section increases. Is there an inverse function for this or a way to undo it? I want to see more of the waveform.

**Comment by drom** [comment]
@deathbysushi well, if you keep clicking `proportions` it will wrap around in 6 clicks.

**Comment by deathbysushi** [comment]
Thanks! Didn't know it looped around. After pushing it 3 times, I was afraid to push it more and squish the waveform further.
