### ISSUE TITLE
Support downloading scripts over https

### ISSUE THREAD

**Issue by jnikula** [drom/wavedrom#177]
I get privacy error for trying to access https://wavedrom.com/WaveDrom.js or https://wavedrom.com/skins/default.js. This makes it hard to use WaveDrom from wavedrom.com within pages served over https.

**Comment by drom** [comment]
You should load scripts from CDN. See https://github.com/drom/wavedrom#html-pages for details.

**Comment by jnikula** [comment]
Thanks; either I've missed that completely or it's been added after I've read the page.
