### ISSUE TITLE
0 byte PNG files again

### ISSUE THREAD

**Issue by edotesla** [drom/wavedrom#180]
Please describe your system environment before submitting your Issue.
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Windows 7

Click Export Png and each time the file is 0 bytes.  This morning it was working fine.
Seen on multiple computers.

Thanks,
/Ed

**Comment by drom** [comment]
@edotesla It is issue for the https://github.com/wavedrom/wavedrom.github.io
moving here https://github.com/wavedrom/wavedrom.github.io/issues/27
