### ISSUE TITLE
Link to the tutorial inside the Wiki is broken

### ISSUE THREAD

**Issue by AntonKrug** [drom/wavedrom#197]
https://github.com/drom/wavedrom/wiki/WaveJSON 
has a link which is broken

**Comment by AntonKrug** [comment]
Probably pointing to both https://wavedrom.com/tutorial2.html and https://wavedrom.com/tutorial.html would be beneficial.

**Comment by drom** [comment]
Wiki is significantly outdated. I fixed links to the tutorial.
