### ISSUE TITLE
Add overline to signal name

### ISSUE THREAD

**Issue by whc2001** [drom/wavedrom#206]
Please add a way to mark a signal name with overline as it's quite useful to express low-enabled signal. It's better to use a particular character to individually mark each character that needs to be overlined than overline the entire signal name (like [this](https://github.com/drom/wavedrom/issues/100)). For example, in Altium Designer, writing `R/W\` for pin name will result in ![read_ write](https://user-images.githubusercontent.com/16266909/46911530-9c254900-cf2c-11e8-8a65-8062e66243a4.gif). Thanks.

**Comment by drom** [comment]
Overline is supported with `<o>text</o>` 
for other markup see https://github.com/drom/tspan

**Comment by whc2001** [comment]
Awesome, thanks!
