### ISSUE TITLE
PNG background options

### ISSUE THREAD

**Issue by jimga150** [drom/wavedrom#369]
I am using the web version.

When exporting to a PNG, it looks like It has a transparent background, which makes the waveforms illegible if a dark background is used in whatever image viewer someone is using. Can the PNG be modified (or given the option) to use a solid white background?

With white background:
<img width="915" alt="wavedrom screenshot light" src="https://user-images.githubusercontent.com/17803304/181616323-f9829d05-642d-4022-96fb-5e4a0ff5e7f5.PNG">

With black background, such as in the default windows photo app:
<img width="713" alt="wavedrom screenshot" src="https://user-images.githubusercontent.com/17803304/181616325-128582fd-b574-4962-a334-e082dc1cac9d.PNG">

**Comment by rgetz** [comment]
+1 for handling dark mode applications

**Comment by grant-h** [comment]
For many, the default on GitHub is dark mode, which makes renderings illegible.

**Comment by CAESIUS-TIM** [comment]
- vscode
  - version: 1.83.1
  - color theme: Dark Modern (Default Dark Modern)
- Markdown Preview Ext.: markdown-all-in-one 
  - version: v3.5.1
  - preview theme: None
  - [Repository](https://github.com/yzhang-gh/vscode-markdown)
  - [Marketplace](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)

```markdown
\`\`\`wavedrom
{ 
  signal: [
    { name: "SIO_C", wave: '01.0.1.0.1.0|1.'},
    { name: "SIO_D (IN)", wave: '1.0.=...=...|010', phase: 0.5 },
    { name: "SIO_D (OUT)", wave: 'x...=...=...|...', phase: 0.5 },
  ],
  config: {
    hscale: 1,
  },
}
\`\`\`
```
<s>How to escape the backtick symbol in GitHub Markdown? Different from testing in vscode.</s>


![image](https://github.com/wavedrom/wavedrom/assets/60285058/6efd7ed8-c3d3-4d79-94dc-1d50430c8137)

# Dark skin

But no stable or merged.

#366
#114
