### ISSUE TITLE
timeline labels

### ISSUE THREAD

**Issue by drom** [drom/wavedrom#40]
_From [alex.d...@gmail.com](https://code.google.com/u/112117906073099522199/) on February 02, 2012 22:45:34_

If someone want to change labels on the bottom of the timing diagram 1 2 3 ...
we can provide the way of overwriting the timeline labels from config section:
{
  "signal" : [ ... ],
  "config" : { "timeline" : ['1','2','3','100','A'] }
} https://groups.google.com/forum/?fromgroups#!topic/wavedrom/KlqxDiVoBMo

_Original issue: http://code.google.com/p/wavedrom/issues/detail?id=40_

**Comment by drom** [comment]
Was implemented using ```foot.tock``` property:
```
{signal: [
  {name:'clk',         wave: 'p....' },
  {name:'Data',        wave: 'x345x', data: 'a b c' },
  {name:'Request',     wave: '01..0' }
],
 foot:{
   tock:'1 2 3 100 A'
 }
}
```

**Comment by mne91** [comment]
The previous JSON string prints a "zero" `0` at the end of the `tock`s. Is this a bug?

**Comment by sonebu** [comment]
don't know if it's a bug but it seems like adding a space at the end of the string fixed that trailing zero for me, i.e., `tock:'1 2 3 100 A '` rather than `tock:'1 2 3 100 A'`
