### ISSUE TITLE
Splitter ( | ) extends data cycle

### ISSUE THREAD

**Issue by drom** [drom/wavedrom#48]
_From [alex.d...@gmail.com](https://code.google.com/u/112117906073099522199/) on June 16, 2012 02:58:12_

I am having an issue representing a counter where I want to show the first couple counts, then use a | to put a gap and show the last couple counts before an action occurs.  If I use the | character it extends the previous count and makes it look like the count lasts two cycles.  is there something I am missing that could represent this better? https://groups.google.com/d/topic/wavedrom/HCjs3L_VyQM/discussion

_Original issue: http://code.google.com/p/wavedrom/issues/detail?id=48_

**Comment by dithomasrc** [comment]
I ran into this issue today. I hope it can get fixed. Otherwise absolutely amazing tool. Hardware designers arent used to having good tools.

**Comment by drom** [comment]
Please use sub-cycle feature alone with gap symbol `|`

Like `{ wave: '=<x|>=' }`
