### ISSUE TITLE
Ability to hide a nodes' label

### ISSUE THREAD

**Issue by drom** [drom/wavedrom#63]
_From [c...@braehler.com](https://code.google.com/u/105311911521959878237/) on February 12, 2013 00:12:35_

What is the expected output? What do you see instead? I would like to be able to suppress a node label. Please provide any additional information below. It's just an idea, but should be easy to implement. At the moment, whenever I place a node, the corresponding symbol is placed in the waveform. But sometimes I just want to be able to use the nodes without additional cluttering in the picture.

My suggestion: Don't print labels for uppercase letters.
One could use the classic abcde for labelled nodes and ABCDE for those that can be referred to, but which will not be printed.

_Original issue: http://code.google.com/p/wavedrom/issues/detail?id=63_

**Comment by fredolin92** [comment]
I am new in the Wavedrom coding! I really like to use this option ;) How can I use it with the online editor? Can you give an example?

**Comment by Whatnever** [comment]
There is a bug with this: Arrows infered with "<->" are not at the end of the line.
They look something like this ----->-

**Comment by drom** [comment]
@Whatnever could be more specific and provide an example that brakes?

**Comment by jagjordi** [comment]
Could you specify what config option should be used to hide the labels? Thank you very mych

**Comment by BasF0** [comment]
> Could you specify what config option should be used to hide the labels? Thank you very mych

Was wondering the same. Capitalizing the node labels hides them.

**Comment by drom** [comment]
Lower case letters are visible
Upper case letters are hidden
